### ISSUE TITLE
Which compilers are supported?

### ISSUE THREAD

**Issue by ldionne** [tzlaine/yap#1]
It won't build with Clang 3.8 and GCC 6. It would be nice to document which minimum versions are required.

**Comment by tzlaine** [comment]
This is an excellent point.  I'll add docs that indicate this, but Clang 3.8+ and GCC 6+ should both work.  Are you using the c++14 branch?  That's the most usable one.  The master branch might only work with Clang-SVN (that's all I've tried).

**Comment by ldionne** [comment]
Oh, I'm doing everything on master.
