### ISSUE TITLE
consider a different name

### ISSUE THREAD

**Issue by badair** [tzlaine/yap#17]
Googling "C++ Yap" yields a bunch of other stuff. I think this is a really cool and important project, so I think it deserves a more memorable name.

**Comment by daixtrose** [comment]
Yeah. But good names are rare. It took only three months to find the unique name ```daixtrose``` ...

**Comment by nuskorpios** [comment]
However, googling "Boost yap" gives this repository as the second result, losing the first position only to the Boost.YAP documentation page.

**Comment by daixtrose** [comment]
I tested again and can confirm that for English language settings everything is fine. It is only when your langauge settings are different, then you might not see this library. 

Is https://www.dcc.fc.up.pt/~vsc/Yap/ related to your effort? Same effect as with boost::hana and SAP's hana ...

**Comment by nuskorpios** [comment]
@daixtrose, about your link, *AFAIK*, Prolog is a language based on first-order logic, which has nothing to do with the ET mechanism Boost.YAP proposes. This is a simple coincidence, when both are using "Yet Another " to describe their projects. If fact, there's another project called [Yet Another Previewer][yap], used by MiKTeX.

[yap]: https://math.vanderbilt.edu/schectex/wincd/tips_yap.htm

**Comment by tzlaine** [comment]
Nope.  I like YAP.
