### ISSUE TITLE
Consider evaluation of expression on destruction;

### ISSUE THREAD

**Issue by correaa** [tzlaine/yap#26]
Would it be possible to evaluate (by default or as an option) to evaluate expression upon destruction. 

For example, normally in expression template libraries, one has some sort of evaluate function,

```
terminal a = ...
terminal b = ...
terminal c = ...
evaluate(a = b + c);
```

In principle, destruction on `;` could trigger the evaluation. 
```
a = b + c;
```
I think it is possible to do because subexpression could be flagged not to evaluate upon their destruction.

Another example from hello_world:

```
#include <boost/yap/expression.hpp>
#include <iostream>
int main (){
//traditional:    
// evaluate(boost::yap::make_terminal(std::cout) << "Hello" << ',' << " world!\n");
// automatic evaluation on destruction of a temporary
    boost::yap::make_terminal(std::cout) << "Hello" << ',' << " world!\n";
// or at least:    
//    boost::yap::make_auto_terminal(std::cout) << "Hello" << ',' << " world!\n";
    return 0;
}
```
This way the syntax will be more natural. 
What do you think?

**Comment by tzlaine** [comment]
For now, I'm against this approach.  I think evaluations (and transforms) should be explicit.  While the "_auto" add to make_terminal() might technically count as explicit, I think many users' eyes would jump right past that.

**Comment by correaa** [comment]
Perhaps after our discussion on cppnow you might want to reconsider this. Perhaps I didn't word it well on the original issue post.

**Comment by tzlaine** [comment]
Yes, absolutely.  I have this on my TODO list now.  Thanks again for
bringing it up.

Zach

**Comment by tzlaine** [comment]
Ok, the new example is ready; you're looking for the "Self-evaluating Expressions" exsample:

https://www.boost.org/doc/libs/develop/doc/html/yap.html

This should appear in the next Boost release.

**Comment by correaa** [comment]
Absolutely amazing, this is exact case (axpy) was the first thing I wanted to do the first time I used YAP. 

In principle in the hypothetical conceptual code
```
matrix m1{...}, m2{...}, m3{...}; 
m1 = 3.0 * m2 + m3;
```
The only part that needs to be explicitly yapified (am I using it right?) is `m2` to trigger full control over the expression behavior (including the assignment). no?
```
m1 = 3.0 * expr(m2) + m3;
```

**Comment by tzlaine** [comment]
Yes, that will do it.  If there is an optimization that applies to the left-hand side, though, you'd want to do:

`expr(m1) = 3.0 * expr(m2) + m3;`

In other words, you'd want to YAP-ifiy `m1` too, so that the entire assignment is captured as a transformable, optimizable expression.

**Comment by correaa** [comment]
well, that if somehow© `3.0*expr(m2) + m3` is not implicitly convertible
(self evaluable) to the `matrix` type.

**Comment by correaa** [comment]
On Fri, May 31, 2019 at 1:04 PM Alfredo Correa <alfredo.correa@gmail.com>
wrote:

> well, that if somehow© `3.0*expr(m2) + m3` is not implicitly convertible
> (self evaluable) to the `matrix` type.
>

Can one make `m1 = 3.0*expr(m2) + m3` within the library, or after a
minimal extension.

**Comment by tzlaine** [comment]
I don't really understand the question.  You just "made" `m1 = 3.0*expr(m2) + m3` within the question itself, didn't you?  I don't really get what you're asking.

**Comment by correaa** [comment]
Sorry, the word "work" after the code was missing. 
`matrix m1; m1 = 3.0*expr(m2) + m3`. 
Where `matrix` is a concrete matrix not an expression. Types in the expression somehow imply the need for an evaluation on the rhs.

**Comment by tzlaine** [comment]
Yes, that works.  That's covered in the example by the `operator auto() const` conversion operator on the primary expression template.

One other way you could accomplish this, that I did not show in the example, would be to add a templated ctor to the matrix type:

```
struct matrix {
    template <typename Expr>
    matrix (Expr && expr) {
        // Might be better expressed via SFINAE or via concept.
        static_assert(boost::yap::is_expr<Expr>::value, "a YAP expression is required");
        *this = optimize_and_evaluate(expr);
    }
    // ...
};
```
