### ISSUE TITLE
Build fails on ubuntu with latest libboost-all-dev (1.62.0.1)

### ISSUE THREAD

**Issue by thetechniclord** [tzlaine/yap#27]
I used the following commands to build the project:
`mkdir build`
`cd build`
`cmake ..`
And get the following error while building the examples:
`In file included from /home/tekne/Documents/Projects/yap/example/autodiff_library/autodiff.cpp:13:0:
/home/tekne/Documents/Projects/yap/example/autodiff_library/autodiff.h:11:10: fatal error: boost/serialization/array_wrapper.hpp: No such file or directory
 #include <boost/serialization/array_wrapper.hpp>
`
Including and using the library itself produces no errors. Thanks!

**Comment by tzlaine** [comment]
Thanks for letting me know, but this is a Won't-fix, because that file is available in later versions of Boost (at least as early as 1.64, maybe earlier).
