### ISSUE TITLE
Please create a "Boost Review" tag so we can track issues raised on the Boost ML

### ISSUE THREAD

**Issue by ldionne** [tzlaine/yap#28]
For each issue raised during the review, please create an issue here and tag it with "Boost Review". Then, please include a link to the corresponding GitHub issue when replying on the Boost mailing list. This makes it much easier to keep track of everything and provides clear action items for everyone.

**Comment by tzlaine** [comment]
Sorry, I literally just now saw this.  I really wish GH would email me notifications sometimes.
