### ISSUE TITLE
unhelpful error message when using a class template which doesn't satisfy the expression concept

### ISSUE THREAD

**Issue by rgrover** [tzlaine/yap#73]
The following definition of an expression template attempts to use std::tuple as the element container. 
   
```C++
    template <expr_kind Kind, typename T>
    struct m_expr {
        constexpr static expr_kind kind = Kind;
    
        using tuple_type = std::tuple<T>;
    
        tuple_type elements;
    };

    int main()
    {
        constexpr auto e = make_terminal<m_expr>(1);
    }

```

It fails to compile with a unhelpful error message `error: static_assert failed "evaluate() is only defined for expressions."`

I propose the following version of `is_expr<>` as a remedy.

```C++
    template<
        typename Expr,
        typename = detail::void_t<>,
        typename = detail::void_t<>>
    struct is_expr : std::false_type
    {
    };

    template<typename Expr>
    struct is_expr<
        Expr,
        detail::void_t<decltype(detail::remove_cv_ref_t<Expr>::kind)>,
        detail::void_t<decltype(std::declval<Expr>().elements)>>
        : std::true_type
    {
        static_assert(
            std::is_same<
                std::remove_cv_t<decltype(detail::remove_cv_ref_t<Expr>::kind)>,
                expr_kind
            >::value,
            "expression template needs a yap::expr_kind tag");
        static_assert(
            hana::is_a<
                hana::tuple_tag,
                decltype(std::declval<Expr>().elements)
            >(),
        "expression template needs a hana tuple like container for elements");
    };
```

**Comment by rgrover** [comment]
Maybe the fall-back instantiation of is_expr should also static_assert?

**Comment by tzlaine** [comment]
This is best we can do in this case, afaict.  We cannot add the static_asserts) above without breaking SFINAE uses of is_expr<>, which is one of its major use cases.  If you have another way to report errors more gracefully without resorting to static_assert(), I'd be happy to use it.

**Comment by tzlaine** [comment]
They do.  usually it's just static_assert(is_expr<Expr>::value, "Expr must be a YAP expressions") or similar.  It's then up to the user to figure out why Expr is not a model of Expression.  The requirements are extremely simple for the user to check/audit/enforce.
