### ISSUE TITLE
expr_kind documentation shows pre_dec as `-` not `--`

### ISSUE THREAD

**Issue by LegalizeAdulthood** [tzlaine/yap#84]
See https://tzlaine.github.io/yap/doc/html/boost/yap/expr_kind.html

Same problem for `post_dec`

**Comment by LegalizeAdulthood** [comment]
The <dd> blocks in this web page are also formatted slightly oddly.  I would expect the values to all be formatted as fixed-width font, but it is varying.  Sometimes portions are fixed-width and others are not.

**Comment by tzlaine** [comment]
Thanks for pointing this out.
